services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:33306/crofle1?serverTimezone=UTC
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=1234
#      - SPRING_REDIS_HOST=redis
    deploy:
      resources:
        limits:
          memory: 12GB  # 파일 처리를 위한 여유 메모리
    networks:
      - app-network

  mysql:
    image: mysql
    ports:
      - "33306:3306"
    environment:
      - MYSQL_DATABASE=crofle1
      - MYSQL_USER=crofle_user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: